CREATE DATABASE "bookapi";

GRANT ALL PRIVILEGES ON DATABASE "bookapi" TO "postgres";

\c "bookapi";

DROP TABLE IF EXISTS "borrowing";
DROP TABLE IF EXISTS "book";
DROP TABLE IF EXISTS "user";

CREATE TABLE IF NOT EXISTS "user" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "book" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "borrowing" (
  "id" SERIAL PRIMARY KEY,
  "borrowedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "returnedAt" TIMESTAMP,
  "userId" INT,
  "bookId" INT,
  "score" INT,
  "status" VARCHAR(255),
  CONSTRAINT "FK_userId" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "FK_bookId" FOREIGN KEY ("bookId") REFERENCES "book"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
